### ISSUE TITLE
Avoid switching: Refresh Goals immediately once changes are added in colab type goals

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1050]
It's been observed that we need to switch pages to get the notification symbol. 
Expected Output: as soon as changes are added and the promise is resolved refresh the page content.

**Comment by tijlleenders** [comment]
I'm not sure what this issue is about.
Can you give me the specific steps I need to do to test if this is working now with the PR?

When I add a collaboration from Inbox the view automatically switches to MyGoals, but I don't see that goal in MyGoals. 
I need to switch to Inbox and back again to make it  appear...
