### ISSUE TITLE
change the bullets

### ISSUE THREAD

**Issue by i-AmanRawat** [tijlleenders/ZinZen#1198]
• change semi circle bullets, they are not looking good. It seems like it is some sort of styling mistake because of which only half circle is visible on the screen.

<img width="353" alt="Screenshot 2023-05-07 at 1 34 11 PM" src="https://user-images.githubusercontent.com/94544552/236665569-8edc8681-d1ae-4f73-bc9f-6dc9310cf9ba.png">

some other bullet like we have in ms word.
Actually the current bullets is not that much soothing and is large in size as per me. our focus must go on goals that we have written not on those bullets so that's why I think we should use small size bullets.

**Comment by tijlleenders** [comment]
Thanks for the feedback @i-AmanRawat !  

I do agree that this could be interpreted as a styling mistake. We'll take it into consideration foe the next iteration of the theme.  

The challenge is to find a color indicator `goals` on this page that also serves as a type indicator - so we won't be confused with the color/typr indicator of the `tasks` on the MyTime page.  

For now we consider this low prio - but feel free to come up with a proposal/design.  
It should be smooth, rounded, relaxed and natural - not hard/modern/sharp-edged.

**Comment by tijlleenders** [comment]
@i-AmanRawat 
The motivation for moving the bullets half off-sceen was to save screen space for text.  
This was obviously not optimal as I can easily imagine people finding this weird. Also, the saved space is actually being used by the notification indicator, not the text, so in the end there is no benefit.  

I can come up with three solutions:  
1. Complete the half circle into a closed structure, so a 'D' shape instead of reversed 'C'
2. Flatten the circle to a stripe along the edge of the screen
3. Make the circle smaller and center is so it appears on-screen completely.  

**What do you think?**  

My preference would be 3 - but it is technically a little more involved - since the 'notification indicator' will now have to appear in a different way. It could be placed in the center of the new, centered bullet, until we find a better idea. This has the added benefit of making it easier to press the notification indicator.  

Visualization of solution 3, including a notification dot:  
<img width="353" alt="image" src="https://github.com/tijlleenders/ZinZen/assets/44887755/e9eb7658-d585-4fa0-8d4f-07d6e88a5da8">

**Comment by tijlleenders** [comment]
@i-AmanRawat We're moving forward and implementing this in coming weeks as per previous comment.  
Let us know if there's anything you'd like to add.

**Comment by i-AmanRawat** [comment]
3rd solution sounds good to me

**Comment by tijlleenders** [comment]
@i-AmanRawat Thanks for you input. The circles will definitely be smaller - but still with a semi-transparent interior so as to differentiate the Goals from the Tasks on the MyTime page.

**Comment by tijlleenders** [comment]
Resolved by #1408
