### ISSUE TITLE
Closing inbox takes user back to previously visited page

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1248]
**Describe the bug**
Upon opening the inbox and then navigating to a different page without closing it, when get back to inbox page and try to close it, instead of closing the inbox user is navigated back to the page he visited.

**To Reproduce**
1. Go to 'My Goals' page and click inbox button.
2. Without closing the inbox, navigate to different page from bottom navigation.
3. Get back to "My Goals" page and try to close the inbox by clicking envelope icon.
4. You are sent back to the page you visited recently.

**Expected behavior**
Bug should be resolved.

**Screen Recording**
https://github.com/tijlleenders/ZinZen/assets/90821253/59ec5277-44f6-483e-a766-8502fae537f7

**Comment by Tushar-4781** [comment]
@vinaybadgujar102  Your concern is valid but its a tricky one let's understand that situation first when we click the native back button it takes you the previous state now that could be a page or sub component like subgoals or a popup ok ? now if we consider your case then in that if you simply press back button to go back to myGoals instead of clicking it via bottom nav then it would work just fine. Now, since you did via bottom nav 3rd step just to close the inbox which is kept open by you earlier. now solution would be that if you have moved to other page instead of pushing into history we replace the current one but that behavior is not fruitful for other scenarios. So that's why use native back button to go back to previous page or state ( where you left ) instead of choosing from bottom and even if you choose then use back to rollback to that state.

**Comment by vinaybadgujar102** [comment]
I will try to work on this.

**Comment by tijlleenders** [comment]
@Tushar-4781 Do we still use an inbox?  
I see no references in the code to the `inboxIcon` and `openEnvelopeIcon`.  

There's a use-case to bring them back in the future though - for messages that can't be related to a specific Goal.

 For now I think #1248 can be closed as unplanned?

**Comment by Tushar-4781** [comment]
@tijlleenders we don't have any inbox feature now. this issue doesn't exist anymore
