### ISSUE TITLE
Back button in MyGoals should move up first

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1279]
**Describe the bug**

**To Reproduce**
1. Go to a sub goal
2. Click on MyTime or Journal
3. Go back to MyGoals
4. Press native back button or parent breadcrumb
5. See that you're not navigating 'up' the breadcrumb

**Comment by Tushar-4781** [comment]
@tijlleenders this ain't a bug actually, that's how the browser works, if after 2nd step you want to go to **back** to my goals then you should have used native back in that case you will achieve your desired output. since you used bottom navbar it pushed to history.

nevertheless, I will introduce a patch that will check if you are visiting back to previous page where you are coming from.
