### ISSUE TITLE
Quick theme toggle button disappears from title bar 

### ISSUE THREAD

**Issue by Shubham-Praj** [tijlleenders/ZinZen#1531]
**WON'T FIX - Not a bug in my view.**
If you believe this is a bug - please upvote this issue.

**Describe the bug**
When the user switches from light theme to dark theme using the theme toggle button in title bar, the toggle button disappears in dark mode

**To Reproduce**
When present on light mode, toggle the theme to dark mode

**Expected behavior**
The quick theme toggle button should be present on dark mode as well.
When present in dark mode the quick theme toggle button should show a bright bulb icon (which on click toggles to light mode)

**Screenshots**
Light theme 
![image](https://github.com/tijlleenders/ZinZen/assets/62180559/ddbb271d-6156-48ee-831f-5758c74ffee8)

Dark theme
![image](https://github.com/tijlleenders/ZinZen/assets/62180559/8dbf6e81-6bf8-4510-a528-a113336eb111)

**Comment by tijlleenders** [comment]
@Shubham-Praj Thanks for reporting this.

I understand how this can be confusing. The quick switch is time dependant. It obly appears for dark when dark mode is probably preferable and vice-versa - see #1380.

So not a bug - it's a feature...
Leaving the quick-switch icon permanently wpuld crowd the header.

... but I'll leave this one open so people who find this confusing as well can vote to change this behavior - or propose a better solution.

**Comment by devndevs** [comment]
I appreciate the intention behind the feature designed to declutter the header, though it might be a bit perplexing for users not yet acquainted with this functionality or its rationale.

For instance, when I selected the "Light Mode" icon this morning, I was initially taken aback by its disappearance. However, I managed to locate the toggle in the menu. This experience, albeit minor, highlighted an opportunity to enhance the UI's intuitiveness.

It's also worth noting that a significant number of users—over 80% according to several surveys—express a preference for Dark Mode, with some findings even suggesting a preference as high as 94%. This is an important consideration, especially for those moments when users, like myself, are navigating to adjust their settings in the dropdown menu. Ensuring the toggle's constant accessibility could greatly improve user satisfaction.

In light of this, I'd like to propose a couple of constructive suggestions:

1. If the objective is to minimize header clutter, perhaps re-evaluating the necessity of the quick toggle could be beneficial. It seems that in many contemporary applications, the Dark Mode setting is tucked away within the settings menu, reserved for one-time adjustments rather than frequent toggling. This approach could simplify user interactions and streamline the overall experience.
2. Maintaining the adjustment I recommended in issue #1819 could offer a more seamless experience, particularly for those who may not realize the feature's time-sensitive nature.

I believe these adjustments could further refine the user interface, making it even more user-friendly and aligned with prevalent user preferences.

**Comment by tijlleenders** [comment]
Great stuff @devndevs 

I was not aware of this.

Based on your info I think we'll make dark mode the default - and put the toggle in the menu.

**Comment by devndevs** [comment]
@tijlleenders is it too late for me to be assigned on this issue? Not sure if it will reflect on my profile that I had completed an issue. this would be helpful as I am in the market for a job and would help show recruiters that I am active.

**Comment by tijlleenders** [comment]
@devndevs Sure np. Contact me on work@zinzen.me or Signal +31 6 4979 4614 or LinkedIn so we can chat about your job requirements.
