### ISSUE TITLE
The CI should build + test the app to resolve build errors at the PR level - starting locally

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#154]
I have had 3 consecutive build errors that were marked error-free by the current CI and approved for merging as a PR. The functionality of the CI should be to detect all build errors. I would once again recommend using Vercel in reference to #42 as it not only builds the app for every PR but serves it on a unique URL too. For the time being we should build the app on local before making PRs

**Comment by tijlleenders** [comment]
Good point. Since it is an offline app a local build + test seems like a good idea - always.
Even if we have Vercel we should only push to the repo after running a local build + tests, right?

Are we triggering build/test/refresh local browser on every save to a file?
What is the extension/tool setup we use?

This is another advantage of having a standalone offline-first anonymous app: No need for a centralized CI. It should be a formality to merge code to the central repo. Commercial companies can't do this without extensive mocking - but we can.

**Comment by pulkitvyas08** [comment]
> Good point. Since it is an offline app a local build + test seems like a good idea - always. Even if we have Vercel we should only push to the repo after running a local build + tests, right?

Yes, definitely. Running local builds is essential but even if not then PR level builds with Vercel would also be fine. Let's see how much the Vercel workflow is impactful on this issue and then revisit the possibilities of changing something in the CI

> Are we triggering build/test/refresh local browser on every save to a file? What is the extension/tool setup we use?

Right now it is the Webpack's [Hot Module Replacement](https://webpack.js.org/concepts/hot-module-replacement/), the default create-react-app configuration. It is slow and buggy but works for the most part, to solve issues with this HMR I was recommending using ViteJS in #139 

> This is another advantage of having a standalone offline-first anonymous app: No need for a centralized CI. It should be a formality to merge code to the central repo. Commercial companies can't do this without extensive mocking - but we can.

Right, that is an interesting perspective on this, thanks for bringing it up!
