### ISSUE TITLE
Write tests for collaboration feature

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1678]
**Is your feature request related to a problem? Please describe.**
Ex. It's not possible to review collaboration features and its cases manually in PRs

**Describe the solution you'd like**
Write tests for collaboration feature.

**Additional context**
Create 3 users. one as sharer and 2 as collaborator check if sharing between all three works smoothly. create test cases for example like A shares with B where C is receiving when B accepts those changes. check that C is receiving only the changes he should be receiving. consider such scenarios and write tests

**Comment by vinaybadgujar102** [comment]
Hey @tijlleenders, can you create a doc that explains how the sharing and collaboration feature works? This will help:
-  Users to understand how to use this feature
-  Contributors to understand how this feature is expected to work

**Comment by tijlleenders** [comment]
Hi @vinaybadgujar102, I don't believe a doc should be necessary.  The UI should be intuitive enough to 'just work'.  
Let's have a session when you have time so I can understand in detail what puzzles you - and figure out how we can simplify the UI.  
If necessary we can even use the [antd tour component](https://ant.design/components/tour).

**Comment by vinaybadgujar102** [comment]
I only want to know the difference between sharing (sharer) and collaboration (collaborator).

**Comment by tijlleenders** [comment]
Ah ok,  
Let me attempt to explain this: A **collaboration** happens when a goal **shared** with you ... is also placed in your 'My goals' by you.

So a collaboration always starts by Alice sharing a goal with Bob (you).  
This is called sharing - and if Bob doesn't do anything (except accepting Alice as a contact if this is the initial share) - then there will not be any collaboration. Bob will see whatever Alice has shared with him when he goes to 'partner mode' in his app. So it's kind of like if Alice shared her calendar with Bob. He can see whatever appointments Alice has - but they don't have joint appointments.

Now from an initial shared goal shared by Alice, if this is something Bob is interested in, he can upgrade the goal shared with him to a collaboration (via goal circle menu in Alice's goals). Continuing the calendar sharing analogy: Bob would invite himself to an appointment on Alice's calendar.  
The goal will now also be Bob's goal - and will appear as such in his goal list (with a two person collaboration icon to signal this is something being worked on by not only him, but other too.  

In both cases, Bob can edit the goal shared with him:  
- if he edits a goal purely shared with him from the partner mode - this triggers a **suggestion** to Alice - without modifying it, as Alice is the sole owner and needs to accept the suggested changes first
- if he edits a goal he is collaborating in from Bob's 'My goals' - since he is also owner of this goal, this will immediately edit the goal on his side - and trigger a **suggestion** to Alice - who may or may not accept the change, since she is owner of her version of the goal.
