### ISSUE TITLE
[BUG] Overflow is not scrolling through the content on the main page

### ISSUE THREAD

**Issue by rupali-codes** [tijlleenders/ZinZen#2057]
**Describe the bug**
Whenever a user open's their dashboard, its not letting the user to scroll on the page. Its blocking the scroller, when I am reducing the screen-size its showing me more content on the list but by default, its not showing it properly.

**Expected behavior**
It should have a scrollbar on overflow, if the content is overflowing then user should be able to scroll through the content.
On mobile scrollbar should not show.

**Screenshots**
1. How it's showing by default 
![image](https://github.com/user-attachments/assets/b3f04a22-cc7c-48d2-80a7-0bde712635e8)

2. When i'm reducing the screen-size
![image](https://github.com/user-attachments/assets/04a9a0f0-3700-4863-a3e8-3d59dc0e8056)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave

**Smartphone (please complete the following information):**
It works fine on smartphone.

**Comment by tijlleenders** [comment]
Thanks for signalling this @rupali-codes !

**Comment by rupali-codes** [comment]
hi @tijlleenders, could you assign it to me?

**Comment by tijlleenders** [comment]
Of course, thanks!

**Comment by tijlleenders** [comment]
@rupali-codes I'm not sure if I understand the bug.  
Sorry I didn´t test it extensively earlier before accepting.  

On Chrome (and probably Brave):  
- scrolling works with mouse scroll (or two finger mousepad)   
- a scroll bar **is not visible** on overflow

  
On Firefox:
- scrolling works with mouse scroll (or two finger mousepad)   
- and scrollbar is visible on overflow

So the problem is purely that the scrollbar is not visible on Chrome (and probably Brave), right?
