### ISSUE TITLE
Make the app work offline with service workers

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#224]

**Comment by tijlleenders** [comment]
@mallikarai05 Is this done already?
If not let's reopen it and keep it for another sprint.

**Comment by mallikarai05** [comment]
@tijlleenders this issue was not visible on the project board, so I closed it and made another there. I haven't worked on it yet. But I think I can start today, I have time

**Comment by tijlleenders** [comment]
Yeah,

When an issue is created they don't ho to the Backlog column automatically. Which is good because then we can determine the priority and effort before we add it.

If you're done with everything we wanted to do this week then fine to work on this. Otherwise I would suggest to stick with the process and finish what we intended to finish first.
