### ISSUE TITLE
Convert the project to typescript and fix errors

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#237]
Right now the project is React Javascript.

The project needs to be converted to typescript.
There's a [howto on converting **an existing project** here]( https://create-react-app.dev/docs/adding-typescript/).

**Comment by pulkitvyas08** [comment]
Please note that some parts of this have already been implemented. For example, the typescript npm packages, as well as `tsconfig.json`, are already there in the project. Check them in `package.json` and project root. This was done as part of migrating the build system to `Vite` in #221 
What remains to be done is the following:
- [ ] Configuring the strictness of type checking within the project inside `tsconfig.json`
- [ ] Changing `.jsx` to `.tsx` and `.js` to `.ts`
- [ ] Adding interfaces and types
- [ ] Adding custom global interfaces (using `global.d.ts`) for packages that are not part of `@types/`

@Tushar-4781 maybe you would like to take point on this.

Please make sure to keep the following things in mind:
- `tsc --init` and other commands have already been executed and the relevant packages are there in the app. Modifications made to `tsconfig.json` due to executing those commands once again might cause breaking changes.
- Make frequent commits with small milestones as this is a big change to the overall project and will create conflicts for sure 
- Expanding on the above point, avoid using `@ts-ignore`, and wherever you don't see a suitable fix for a type check and are forced to use it, just make a commit and start a discussion in the PR itself.

I have some experience in migrating JS projects to TS, so I understand how frustrating the process could be in some cases. Hopefully, we will get this done ASAP

**Comment by pulkitvyas08** [comment]
@tijlleenders the title of the issue says "and fix errors" is this referring to any particular error present in the project at the moment or about fixing the errors that would be cause by converting to TS?

**Comment by tijlleenders** [comment]
Good question @pulkitvyas08 .  
Let's clarify: it is about fixing the errors caused by the conversion.

**Comment by pulkitvyas08** [comment]
@Tushar-4781 please don't consider my work on #117 as a blocker for this task. I will implement this feature in TypeScript itself to make it easier for everyone involved

**Comment by Tushar-4781** [comment]
Resolved #283
