### ISSUE TITLE
Make the design for the My feelings page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#313]

**Comment by mallikarai05** [comment]
When you click on a date you are directed to the add feelings page, where you can add more for that particular day.
When you click on a feeling it gets removed.
The additional plus button next to the feeling can be used to add the reason for a particular feeling.
![image](https://user-images.githubusercontent.com/73054648/168482104-ede94a47-ce32-41b5-8c21-7f73f6d8ac39.png)

Should there be a blank for the day you haven't logged anything? (I personally think there should be one)

**Comment by tijlleenders** [comment]
Hmmm... Isn't the plus button a little too significant, especially if there is a long list.

Maybe only have the Edit / Delete appear once you click on the feeling as a sub menu (juat like with goals)? This also keeps the interface consistent.

What if there is multiple feelings logged on a day?

Can you show how it would look if there's a note? Is it als ways showing, hidden by default or showin partially with an ellipae ("...")?

**Comment by tijlleenders** [comment]
Agree that skipped days should show.

For the days you haven't logged anything only the + button would show?

**Comment by tijlleenders** [comment]
Can you update the ZinZen text to the new image?

**Comment by mallikarai05** [comment]
@tijlleenders we cannot have edit and delete buttons here because there can be multiple feelings logged for a day and the tiles are of smaller size, I can prepare a design for it. 
We can have an edit button next to the date if necessary.

![image](https://user-images.githubusercontent.com/73054648/168530477-b3cdb516-941f-48c1-bf28-53d0202d8453.png)

**Comment by tijlleenders** [comment]
Yeah, still too many +'es.
Having an edit next to the date is a good suggestion.

**Comment by mallikarai05** [comment]
The + is for adding the reason for a feeling. I have an alternate design with only one plus.
![image](https://user-images.githubusercontent.com/73054648/168531157-1b328c68-53a7-47b7-bb8c-988fbfc7c4a6.png)
So you can add a reason or image but it won't correspond to a particular feeling but a summary for the whole day. 
I think having one plus button is better and less confusing. 

I have a few ideas on how the note will look, I will prepare the design.

**Comment by tijlleenders** [comment]
This still needs some serious work.

Could you prepare a design where the feelings are more like the menu/navigation/goals buttons?
This would make the whole thing more consistent. Also, you can then click on them to get the sub menu. 

My problem with current design:
- not consistent with rest of app
- not clear how notes/images corresponding to a feeling can be viewed/edited/added
- not possible to have a note/image corresponding to a feeling (restricting to one per day is not a good option)
- not clear at high level how much posititve (happy/gratitude/excited) vs negative (sad/anxious/angry) feeling there were. 
  Maybe have them grouped to left for negative and right for positive? Using colours is tricky as this is culture-dependent.

**Comment by mallikarai05** [comment]
1. As we cannot add colors like in 'My goals' we can keep the color the same for all the logs, with emoji to differentiate. 
![image](https://user-images.githubusercontent.com/73054648/169355793-15b90409-2093-4cc6-8578-c58dde535a73.png)
2. The arrow on the side is the view of the note/image- 
a. If there is none-
![image](https://user-images.githubusercontent.com/73054648/169355932-cffba932-5c60-4703-b02a-5100252ed1b3.png)
b. If there is a note added-
![image](https://user-images.githubusercontent.com/73054648/169356018-6f96c12b-28d1-4725-b9bd-de547bb4b3ac.png)

You can edit by directly clicking on the text box- in case the note exceeds the size there can be 2 options
1. You can click on the expand arrow and be directed to a new page where the whole text and image are visible.
2. You can scroll through the box where the text is displayed but then we might need to enlarge the pop-up menu so that image can be viewed, which will be inconsistent as the same pop-up should be there when there is no note added.

**Comment by tijlleenders** [comment]
Looking good.

We also need a way to quickly see if there is a note or picture for that day. Otherwise you need to check them one by one to see if there is a note... maybe even the first few words with ellipse? ... or something better if you have idea's.

Would put the smileys first so they all align.

**Comment by tijlleenders** [comment]
Looking good.

We also need a way to quickly see if there is a note or picture for that day. Otherwise you need to check them one by one to see if there is a note... maybe even the first few words with ellipse? ... or something better if you have idea's.

Would put the smileys first so they all align.

As for the size of the note. Just limit it to x characters - then there is also no added conplexity for scrolling.

**Comment by mallikarai05** [comment]
The 3 little dots below the emotion logged can tell if there is a note or image for that day or emotion? 
Also if there is a separate note for each emotion it is easier to have them separately as well. In that case, rather than setting a priority (like positive to negative), the user would want to have the emotions/feelings displayed in the order they were logged.
![image](https://user-images.githubusercontent.com/73054648/169650746-686c873d-64ef-4322-a69e-201421a8b9a4.png)

**Comment by tijlleenders** [comment]
Agree with the chronological order and the ellipse for the note. Nice work!

**Comment by tijlleenders** [comment]
Most recent feelings should be at the top.

**Comment by mallikarai05** [comment]
@tijlleenders if for a day I am adding multiple feelings if they are in the chronological order then I can remember my day easily (by what I felt during the day).

**Comment by tijlleenders** [comment]
Agree, so there are two different orders
- the days can be in descending order (today at the top)
- the feelings per day are in ascending order (feelings in the morning at the top, evening at the bottom of the day)

**Comment by tijlleenders** [comment]
"Today" should be the standard date at the top of the screen. If nothing was logged, a + should be shown as in the design for "Sunday, May 8".
