### ISSUE TITLE
Impossible to schedule on roadmap

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#870]
Show the screens for how we are notified of any impossible to schedule tasks upon saving after editing - and on MyTime page.

**Comment by mallikarai05** [comment]
@tijlleenders, Tushar and I had a quick call to discuss this. 
@Tushar-4781 suggested that we show the impossible to schedule tasks for each day separately on the MyTime page. 
So when you expand a particular day, there can be a switch between the scheduled tasks and the unscheduled ones (like how you can switch between MyTime and MyGoals at one click) 
I think it's a good idea to show them separately for each day rather than in a common inbox for impossible-to-schedule tasks(because then you have to mention the time and day)

**Comment by mallikarai05** [comment]
@Tushar-4781 if there is something I left out, please add that!

**Comment by mallikarai05** [comment]
@tijlleenders we can close this issue, the final designs along with the prototype flow have been added to the roadmap.
I made #882 for the dark theme, and will work on it tomorrow!

**Comment by tijlleenders** [comment]
Nice work!
