### ISSUE TITLE
Goals should use duration of type string

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen#878]
The recent build of the scheduler expects duration field of goals to be string. This build was merged but front end is still passing duration of type number, resulting in an error:

![Screenshot from 2023-01-03 09-15-44](https://user-images.githubusercontent.com/51313777/210308231-b1eee7e3-b11c-4394-8325-fc2cb07c9d04.png)

**Comment by egithinji** [comment]
@Tushar-4781 I don't mind working on this. Let me know if I should or you'd rather do it yourself.

**Comment by Tushar-4781** [comment]
@egithinji I m aware that i have to pass duration as a string in the new build as I m working on it I haven't raised a PR or issue on that because the scheduler is giving the wrong output despite of passing duration in string. can you resolve https://github.com/tijlleenders/ZinZen-scheduler/issues/215 this first ?
